---

- name: prepare projects folder
  file: path=/projects state=directory

- name: download sources
  git:
    repo: 'https://github.com/av-ast/scrawler.git'
    dest: /projects/scrawler

- name: run
  docker_service:
    build: yes
    project_name: scrawler
    project_src: /projects/scrawler
  register: output

- debug:
    var: output
