---

- name: define locale
  shell:
    localedef -i {{locale.lang}} -f {{locale.encoding}} {{locale.full}}

- name: set user locale
  lineinfile:
    dest=~/.bashrc
    line="export LC_ALL={{locale.full}} LANG={{locale.full}} LANGUAGE={{locale.full}}"
    state=present
    backup=yes
    insertafter=EOF

- name: install packages
  yum: name={{ item }} update_cache=yes
  with_items:
    - yum-utils
    - git
    - vim
